### PR TITLE
Azure single sign on

### PR DESCRIPTION
**Pull request by nneskildsf**
Local development is still possible despite integration of Azure single sign on.
SSO is turned on in production by definition of the following env variables: `OPENPECTUS_DOMAIN_NAME`, `OPENPECTUS_APPLICATION_CLIENT_ID`, `OPENPECTUS_DIRECTORY_TENANT_ID` and `OPENPECTUS_CLIENT_SECRET`.

User information is available to the frontend at `/id` and offers json:
```json
{
"full_name":"Not Applicable",
"initials":"NA",
"profile_picture":"data:image/jpeg;base64, /9j/4AAQSkZJ[..]",
"roles":["User"]
}
```

### CODE REVIEW

**Comment by nneskildsf** [comment]
This PR uses the ìdentity` python package (https://pypi.org/project/identity/) which is only in version number 0.2.0. Additionally, this package only covers Flask and not FastAPI.
This constraint means that API endpoints are not covered by authentication.

It would likely be a batter basis to use `fastapi-azure-auth` (https://intility.github.io/fastapi-azure-auth/) which is much more mature. However, this library is not really meant for authentication. Instead it accepts a token and can use that to access Azure endpoints.

So at this time, I think the current solution is the lesser evil.

**Comment by jhk-mjolner** [comment]
We can definitely do OAuth 2 authentication on the frontend, and I have done so before. But it is a lot more complicated than handling it through the backend and cookies (still using an idp and OAuth 2, just through the backend).

I'm also concerned that fastapi's own documentation https://fastapi.tiangolo.com/tutorial/security/first-steps/ more or less only talks about implementing OAuth2 against itself as the idp, which isn't what we want. And even when they mention 3rd party idps https://fastapi.tiangolo.com/advanced/security/oauth2-scopes/#about-third-party-integrations they recommend the "implicit flow" which is not the recommended flow any longer https://oauth.net/2/grant-types/password/ So I'm unsure of how well it will support the recommended "auth code with pkce" flow, as I can't remember right know how much is different between those two flows wrt. the backend. I think it might be the same and just require the auth bearer token.

Alternatively, because we host our frontend application on the same domain as our API, we should be able to use OpenID Connect to authenticate with an idp and yet use cookies to simplify the code: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-app-types#web-apps 
This requires a small, simple, non-spa frontend application for the small login flow itself, before browser is redirected to the SPA. And maybe we need some communication with the idp from the backend as well: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-app-types#web-apis which I don't know if we need any python library for.

**Comment by nneskildsf** [comment]
Hi

I had a closer look at `fastapi-azure-auth` and found the following very informative closed issue: https://github.com/Intility/fastapi-azure-auth/issues/41#issuecomment-999705634

Basically, the package is only useful for SPA-like PKCE flows. I will try to see if I can cook this up in Flask.

Br Eskild

**Comment by jhk-mjolner** [comment]
Hmm, yeah, it's probably the sessions stuff we need to be able to use cookies. That is, I think we need something in fastapi to handle user sessions and then only use cookies as a session id. I don't think we can do it in the flask login-only application. If we don't have anything that easily supports user sessions in fastapi, we should probably go with the SPA auth code flow with pkce. 

But maybe this can be used? https://pypi.org/project/fastapi-sessions/

**Comment by nneskildsf** [comment]
Closed since we decided to place authentication in the frontend. The frontend is responsible for getting tokens via PKCE flow and the backend is responsible for validating the token and verifying access to specific resources.

**Pull request closed without merging**
